web:
    image: rus0/magento2-image-7.1:latest
    ports:
        - 8005:80
    volumes:
        - ~/.ssh:/home/magento2/.ssh
        - ./:/var/www/html
        - ./log/nginx:/var/log/nginx
        - ./log/php:/var/log/php-fpm
        - ./build:/build/
    environment:
        - MAGENTO_USER=magento2
        - MAGENTO_VERSION=project-enterprise-edition
        - MAGENTO_DEPLOY_MODE=developer
        - MAGENTO_BASE_URL=http://shoppiland.resp/
        - MAGENTO_BACKEND_FRONTNAME=admin
        - MAGENTO_TIMEZONE=America/Mexico_City
        - MAGENTO_CURRENCY=MXN
        - MAGENTO_LANGUAGE=es_MX
        - MAGENTO_DB_HOST=mysql
        - MAGENTO_DB_USERNAME=root
        - MAGENTO_DB_PASSWORD=mysql
        - MAGENTO_DB_NAME=magento2ce
        - MAGENTO_ADMIN_USER=admin
        - MAGENTO_ADMIN_PASSWORD=admin1234
        - MAGENTO_ADMIN_EMAIL=admin@shoppiland.test
    external_links:
        - mysql
    container_name: prueba-web
